version: '3.0'

services:
    api:
        image: node:8
        entrypoint: ./api-entry.sh
        volumes:
            - ./api/:/api/
            - ./api-entry.sh:/api-entry.sh
        ports:
          - 80:3000

    database:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db/:/data/db/