version: '2.1'


services:
    api:
        image: node:alpine
        entrypoint: ./api-entry.sh
        environment:
            - API_ROUTE_PREFIX=/api
            - PORT=5000
            - JWT_KEY=arstarst1234
        volumes:
            - ./api/:/api/
            - ./api-entry.sh:/api-entry.sh
            - ./data/images/:/api/images/
        depends_on:
            database:
                condition: service_healthy
        ports:
          - 80:80

    database:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db/:/data/db/
            - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
        command: mongod --auth
        healthcheck:
            test: "exit 0"
